#!/bin/bash

# By default, tile all windows
yabai -m config layout bsp

# New window spawns to the right if vertical split, or bottom if horizontal split
yabai -m config window_placement second_child

# Padding
yabai -m config top_padding 12
yabai -m config bottom_padding 12
yabai -m config left_padding 12
yabai -m config right_padding 12
yabai -m config window_gap 12

# Mouse settings
yabai -m config mouse_follows_focus on

yabai -m config mouse_modifier ctrl
# Set modifier + left-click drag to move window (default: move)
yabai -m config mouse_action1 move
# Set modifier + right-click drag to resize window (default: resize)
yabai -m config mouse_action2 resize

yabai -m rule --add app="^System Settings$" manage=off

# Make yabai aware of sketchybar
yabai -m config external_bar all:32:0
